# Generated by Django 3.2.18 on 2023-05-16 09:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=15, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=15, verbose_name='Last Name')),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone No.')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Pick a Date')),
                ('time', models.TimeField(verbose_name='Pick a Time')),
                ('client_notes', models.TextField(blank=True, verbose_name='Leave Your Request Here')),
                ('sent_on', models.DateField(default=datetime.datetime.now)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
    ]
