# Generated by Django 3.2.18 on 2023-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('One on One', 'One on One'), ('PT Package', 'PT Package')], default='One on One', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('4 PM', '4 PM'), ('10 AM', '10 AM'), ('12 PM', '12 PM'), ('8 AM', '8 AM'), ('8 PM', '8 PM'), ('2 PM', '2 PM'), ('6 PM', '6 PM')], default='8 AM', max_length=10),
        ),
    ]
