# Generated by Django 3.2.18 on 2023-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230427_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirm_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('One on One', 'One on One'), ('PT Package', 'PT Package'), ('Consultation', 'Consultation')], default='One on One', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('8 PM', '8 PM'), ('12 PM', '12 PM'), ('10 AM', '10 AM'), ('8 AM', '8 AM'), ('2 PM', '2 PM'), ('4 PM', '4 PM'), ('6 PM', '6 PM')], default='8 AM', max_length=10),
        ),
    ]
