# Generated by Django 3.2.18 on 2023-04-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230427_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
