# Generated by Django 3.2.18 on 2023-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.TimeField(verbose_name='Pick a Time'),
        ),
    ]
