# Generated by Django 3.2.18 on 2023-04-28 09:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('booked_slot', models.CharField(choices=[('8 AM', '8 AM'), ('6 PM', '6 PM'), ('4 PM', '4 PM'), ('2 PM', '2 PM'), ('10 AM', '10 AM'), ('12 PM', '12 PM'), ('8 PM', '8 PM')], default='8 AM', max_length=10)),
                ('client_notes', models.TextField(blank=True)),
                ('sent_on', models.DateField(default=datetime.datetime.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
    ]
