# Generated by Django 3.2.18 on 2023-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_sessionbook_booked_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sessionbook',
            name='booked_slot',
            field=models.CharField(choices=[('6 PM', '6 PM'), ('2 PM', '2 PM'), ('4 PM', '4 PM'), ('8 PM', '8 PM'), ('8 AM', '8 AM'), ('12 PM', '12 PM'), ('10 AM', '10 AM')], default='8 AM', max_length=10),
        ),
    ]
