# Generated by Django 3.2.18 on 2023-05-08 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_sessionbook_booked_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='sessionbook',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='sessionbook',
            name='fname',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sessionbook',
            name='lname',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sessionbook',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionbook',
            name='booked_slot',
            field=models.CharField(choices=[('10 AM', '10 AM'), ('12 PM', '12 PM'), ('4 PM', '4 PM'), ('8 AM', '8 AM'), ('2 PM', '2 PM'), ('6 PM', '6 PM'), ('8 PM', '8 PM')], default='8 AM', max_length=10),
        ),
    ]
