# Generated by Django 3.2.18 on 2023-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20230508_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='date_booked',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionbook',
            name='booked_slot',
            field=models.CharField(choices=[('8 PM', '8 PM'), ('4 PM', '4 PM'), ('6 PM', '6 PM'), ('8 AM', '8 AM'), ('2 PM', '2 PM'), ('10 AM', '10 AM'), ('12 PM', '12 PM')], default='8 AM', max_length=10),
        ),
    ]
