# Generated by Django 3.2.18 on 2023-05-10 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_sessionbook_booked_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbook',
            name='date_booked',
        ),
        migrations.AddField(
            model_name='sessionbook',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Pick a Date'),
        ),
        migrations.AlterField(
            model_name='sessionbook',
            name='booked_slot',
            field=models.CharField(choices=[('12 PM', '12 PM'), ('10 AM', '10 AM'), ('2 PM', '2 PM'), ('6 PM', '6 PM'), ('8 PM', '8 PM'), ('4 PM', '4 PM'), ('8 AM', '8 AM')], default='8 AM', max_length=10, verbose_name='Pick a Slot'),
        ),
    ]
