# Generated by Django 3.2.18 on 2023-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Pick a Slot'),
        ),
    ]
