# Generated by Django 3.2.18 on 2023-05-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.TimeField(null=True, verbose_name='Pick a Time'),
        ),
    ]
