# Generated by Django 3.2.18 on 2023-05-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionbook',
            options={'ordering': ['sent_on']},
        ),
    ]
