# Generated by Django 3.2.18 on 2023-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_alter_sessionbook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.CharField(choices=[(0, '09:00 - 10:30'), (1, '10:30 - 12:00'), (2, '12:00 - 13:30'), (3, '13:30 - 15:00'), (4, '15:00 - 16:30'), (5, '16:30 - 18:00'), (6, '18:00 - 19:30')], default=0, max_length=15, verbose_name='Pick a Time'),
        ),
    ]
