# Generated by Django 3.2.18 on 2023-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.CharField(choices=[('09:00 - 10:30', '09:00 - 10:30'), ('10:30 - 12:00', '10:30 - 12:00'), ('12:00 - 13:30', '12:00 - 13:30'), ('13:30 - 15:00', '13:30 - 15:00'), ('15:00 - 16:30', '15:00 - 16:30'), ('16:30 - 18:00', '16:30 - 18:00'), ('18:00 - 19:30', '18:00 - 19:30')], default='09:00 - 10:30', max_length=15, verbose_name='Pick a Time'),
        ),
    ]
