# Generated by Django 3.2.18 on 2023-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_alter_sessionbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='time',
            field=models.TimeField(verbose_name='Pick a Time'),
        ),
    ]
